//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusBookingEntities : DbContext
    {
        public BusBookingEntities()
            : base("name=BusBookingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TblBiletler> TblBiletlers { get; set; }
        public virtual DbSet<TblCalisanlar> TblCalisanlars { get; set; }
        public virtual DbSet<TblCalisanlarTipler> TblCalisanlarTiplers { get; set; }
        public virtual DbSet<TblMarkalar> TblMarkalars { get; set; }
        public virtual DbSet<TblMasrafTipleri> TblMasrafTipleris { get; set; }
        public virtual DbSet<TblMesajlar> TblMesajlars { get; set; }
        public virtual DbSet<TblMusteriler> TblMusterilers { get; set; }
        public virtual DbSet<TblOtobusler> TblOtobuslers { get; set; }
        public virtual DbSet<TblOtobusMasraflari> TblOtobusMasraflaris { get; set; }
        public virtual DbSet<TblSeferler> TblSeferlers { get; set; }
        public virtual DbSet<TblSehirler> TblSehirlers { get; set; }
        public virtual DbSet<TblSubeler> TblSubelers { get; set; }
        public virtual DbSet<TblKullanicilar> TblKullanicilars { get; set; }
        public virtual DbSet<TblSepet> TblSepets { get; set; }
        public virtual DbSet<TblKoltuklar> TblKoltuklars { get; set; }
    }
}
