//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKoltuklar
    {
        public byte KoltukID { get; set; }
        public string KoltukTuru { get; set; }
        public byte KoltukNo { get; set; }
        public Nullable<int> MusteriID { get; set; }
    
        public virtual TblMusteriler TblMusteriler { get; set; }
    }
}
