//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOtobusMasraflari
    {
        public int OtobusMasrafID { get; set; }
        public int OtobusID { get; set; }
        public int MasrafTipID { get; set; }
        public decimal Tutar { get; set; }
    
        public virtual TblMasrafTipleri TblMasrafTipleri { get; set; }
        public virtual TblOtobusler TblOtobusler { get; set; }
    }
}
