//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOtobusler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblOtobusler()
        {
            this.TblOtobusMasraflaris = new HashSet<TblOtobusMasraflari>();
            this.TblSeferlers = new HashSet<TblSeferler>();
            this.TblSepets = new HashSet<TblSepet>();
        }
    
        public int OtobusID { get; set; }
        public string Plaka { get; set; }
        public byte KoltukSayisi { get; set; }
        public int MarkaID { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual TblMarkalar TblMarkalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOtobusMasraflari> TblOtobusMasraflaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSeferler> TblSeferlers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSepet> TblSepets { get; set; }
    }
}
