//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSepet
    {
        public int SepetID { get; set; }
        public int MusteriID { get; set; }
        public int BiletID { get; set; }
        public int OtobusID { get; set; }
        public int SeferID { get; set; }
        public int SehirID { get; set; }
        public decimal Fiyat { get; set; }
        public decimal ToplamFiyat { get; set; }
        public System.DateTime Tarih { get; set; }
        public System.TimeSpan Saat { get; set; }
        public int KullaniciID { get; set; }
    
        public virtual TblBiletler TblBiletler { get; set; }
        public virtual TblKullanicilar TblKullanicilar { get; set; }
        public virtual TblMusteriler TblMusteriler { get; set; }
        public virtual TblOtobusler TblOtobusler { get; set; }
        public virtual TblSeferler TblSeferler { get; set; }
        public virtual TblSehirler TblSehirler { get; set; }
    }
}
