//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSeferler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSeferler()
        {
            this.TblBiletlers = new HashSet<TblBiletler>();
            this.TblSepets = new HashSet<TblSepet>();
        }
    
        public int SeferID { get; set; }
        public int KalkisSehirID { get; set; }
        public int VarisSehirID { get; set; }
        public int OtobusID { get; set; }
        public int CalisanlarID { get; set; }
        public System.DateTime KalkisZamani { get; set; }
        public System.DateTime VarisZamani { get; set; }
        public decimal BiletTutari { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBiletler> TblBiletlers { get; set; }
        public virtual TblCalisanlar TblCalisanlar { get; set; }
        public virtual TblOtobusler TblOtobusler { get; set; }
        public virtual TblSehirler TblSehirler { get; set; }
        public virtual TblSehirler TblSehirler1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSepet> TblSepets { get; set; }
    }
}
